### ISSUE TITLE
Please rewrite into python3

### ISSUE THREAD

**Issue by fronbasal** [CryptKid/pin_guessable#1]

**Comment by CryptKid** [comment]
NO

**Comment by CryptKid** [comment]
What exactly do you mean?

**Comment by fronbasal** [comment]
The source code you wrote is written in python2. You should rewrite the code into python3.

**Comment by fronbasal** [comment]
All modern and sane linux distributions offer python3 compatibility. This script also is not critical for backwards compatability so it would be sane to delete python2 and just write it in python3.

**Comment by CryptKid** [comment]
Rewrote it and providing both now
